
export const LOGIN = "AUTH.LOGIN";
export const LOGOUT = "AUTH.LOGOUT";
export const PRODUCTS = "PRODUCTS.GET_PRODUCTS";
export const UPDATE_ITEMS = "CART.UPDATE_ITEMS";
export const REMOVE_FROM_CART = "CART.REMOVE_ITEMS";