
export const LOGIN = "AUTH.LOGIN";
export const LOGOUT = "AUTH.LOGOUT";
export const VALIDATE_TOKEN = "VALIDATE_TOKEN";
export const PRODUCTS = "PRODUCTS.GET_PRODUCTS";
export const CATEGORIES = "CATEGORIES.GET_PRODUCTS";